FROM python:3.10-slim
WORKDIR /app
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir numpy pandas scikit-learn joblib kafka-python \
    pyyaml loguru python-dotenv pyarrow
COPY src/ ./src/
COPY configs/ ./configs/
COPY setup.py .
RUN pip install -e . --no-deps --quiet
CMD ["python", "src/streaming/consumer.py", "--live"]
